import { IStanding } from "../../types/standing";
import { EConferences, ETeamLeagueNames } from "../../types/team";

const standings: IStanding[] = [
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 41,
      name: "Washington Wizards",
      nickname: "Wizards",
      code: "WAS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/archive/d/d6/20161212034849%21Wizards2015.png",
    },
    conference: {
      name: EConferences.east,
      rank: 11,
      win: 20,
      loss: 19,
    },
    division: {
      name: "southeast",
      rank: 4,
      win: 6,
      loss: 6,
      gamesBehind: "10.5",
    },
    win: {
      home: 15,
      away: 12,
      total: 27,
      percentage: ".466",
      lastTen: 4,
    },
    loss: {
      home: 15,
      away: 16,
      total: 31,
      percentage: ".534",
      lastTen: 6,
    },
    gamesBehind: "10.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 5,
      name: "Charlotte Hornets",
      nickname: "Hornets",
      code: "CHA",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f3/Hornets_de_Charlotte_logo.svg/1200px-Hornets_de_Charlotte_logo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 9,
      win: 19,
      loss: 18,
    },
    division: {
      name: "southeast",
      rank: 2,
      win: 5,
      loss: 7,
      gamesBehind: "9.5",
    },
    win: {
      home: 14,
      away: 15,
      total: 29,
      percentage: ".483",
      lastTen: 1,
    },
    loss: {
      home: 14,
      away: 17,
      total: 31,
      percentage: ".517",
      lastTen: 9,
    },
    gamesBehind: "9.5",
    streak: 3,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 20,
      name: "Miami Heat",
      nickname: "Heat",
      code: "MIA",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1c/Miami_Heat_-_Logo.svg/1200px-Miami_Heat_-_Logo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 1,
      win: 24,
      loss: 12,
    },
    division: {
      name: "southeast",
      rank: 1,
      win: 11,
      loss: 2,
      gamesBehind: "0.0",
    },
    win: {
      home: 19,
      away: 19,
      total: 38,
      percentage: ".644",
      lastTen: 6,
    },
    loss: {
      home: 7,
      away: 14,
      total: 21,
      percentage: ".356",
      lastTen: 4,
    },
    gamesBehind: "0.0",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 1,
      name: "Atlanta Hawks",
      nickname: "Hawks",
      code: "ATL",
      logo: "https://upload.wikimedia.org/wikipedia/fr/e/ee/Hawks_2016.png",
    },
    conference: {
      name: EConferences.east,
      rank: 10,
      win: 17,
      loss: 18,
    },
    division: {
      name: "southeast",
      rank: 3,
      win: 7,
      loss: 5,
      gamesBehind: "9.5",
    },
    win: {
      home: 17,
      away: 11,
      total: 28,
      percentage: ".483",
      lastTen: 5,
    },
    loss: {
      home: 13,
      away: 17,
      total: 30,
      percentage: ".517",
      lastTen: 5,
    },
    gamesBehind: "9.5",
    streak: 2,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 26,
      name: "Orlando Magic",
      nickname: "Magic",
      code: "ORL",
      logo: "https://upload.wikimedia.org/wikipedia/fr/b/bd/Orlando_Magic_logo_2010.png",
    },
    conference: {
      name: EConferences.east,
      rank: 15,
      win: 8,
      loss: 31,
    },
    division: {
      name: "southeast",
      rank: 5,
      win: 2,
      loss: 11,
      gamesBehind: "25.5",
    },
    win: {
      home: 5,
      away: 8,
      total: 13,
      percentage: ".217",
      lastTen: 3,
    },
    loss: {
      home: 21,
      away: 26,
      total: 47,
      percentage: ".783",
      lastTen: 7,
    },
    gamesBehind: "25.5",
    streak: 4,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 24,
      name: "New York Knicks",
      nickname: "Knicks",
      code: "NYK",
      logo: "https://upload.wikimedia.org/wikipedia/fr/d/dc/NY_Knicks_Logo_2011.png",
    },
    conference: {
      name: EConferences.east,
      rank: 12,
      win: 14,
      loss: 22,
    },
    division: {
      name: "atlantic",
      rank: 5,
      win: 4,
      loss: 7,
      gamesBehind: "10.5",
    },
    win: {
      home: 13,
      away: 12,
      total: 25,
      percentage: ".424",
      lastTen: 2,
    },
    loss: {
      home: 17,
      away: 17,
      total: 34,
      percentage: ".576",
      lastTen: 8,
    },
    gamesBehind: "13.0",
    streak: 3,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 4,
      name: "Brooklyn Nets",
      nickname: "Nets",
      code: "BKN",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/130px-Brooklyn_Nets_newlogo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 8,
      win: 21,
      loss: 13,
    },
    division: {
      name: "atlantic",
      rank: 4,
      win: 7,
      loss: 2,
      gamesBehind: "4.5",
    },
    win: {
      home: 13,
      away: 18,
      total: 31,
      percentage: ".525",
      lastTen: 2,
    },
    loss: {
      home: 15,
      away: 13,
      total: 28,
      percentage: ".475",
      lastTen: 8,
    },
    gamesBehind: "7.0",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 27,
      name: "Philadelphia 76ers",
      nickname: "76ers",
      code: "PHI",
      logo: "https://upload.wikimedia.org/wikipedia/fr/4/48/76ers_2016.png",
    },
    conference: {
      name: EConferences.east,
      rank: 3,
      win: 20,
      loss: 14,
    },
    division: {
      name: "atlantic",
      rank: 1,
      win: 4,
      loss: 7,
      gamesBehind: "0.0",
    },
    win: {
      home: 16,
      away: 19,
      total: 35,
      percentage: ".603",
      lastTen: 6,
    },
    loss: {
      home: 13,
      away: 10,
      total: 23,
      percentage: ".397",
      lastTen: 4,
    },
    gamesBehind: "2.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 38,
      name: "Toronto Raptors",
      nickname: "Raptors",
      code: "TOR",
      logo: "https://upload.wikimedia.org/wikipedia/fr/8/89/Raptors2015.png",
    },
    conference: {
      name: EConferences.east,
      rank: 7,
      win: 21,
      loss: 14,
    },
    division: {
      name: "atlantic",
      rank: 3,
      win: 5,
      loss: 5,
      gamesBehind: "2.5",
    },
    win: {
      home: 16,
      away: 16,
      total: 32,
      percentage: ".561",
      lastTen: 8,
    },
    loss: {
      home: 13,
      away: 12,
      total: 25,
      percentage: ".439",
      lastTen: 2,
    },
    gamesBehind: "5.0",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 6,
      win: 24,
      loss: 15,
    },
    division: {
      name: "atlantic",
      rank: 2,
      win: 7,
      loss: 6,
      gamesBehind: "2.0",
    },
    win: {
      home: 20,
      away: 14,
      total: 34,
      percentage: ".567",
      lastTen: 9,
    },
    loss: {
      home: 11,
      away: 15,
      total: 26,
      percentage: ".433",
      lastTen: 1,
    },
    gamesBehind: "4.5",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 6,
      name: "Chicago Bulls",
      nickname: "Bulls",
      code: "CHI",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d1/Bulls_de_Chicago_logo.svg/1200px-Bulls_de_Chicago_logo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 2,
      win: 23,
      loss: 13,
    },
    division: {
      name: "central",
      rank: 1,
      win: 7,
      loss: 3,
      gamesBehind: "0.0",
    },
    win: {
      home: 23,
      away: 15,
      total: 38,
      percentage: ".644",
      lastTen: 7,
    },
    loss: {
      home: 8,
      away: 13,
      total: 21,
      percentage: ".356",
      lastTen: 3,
    },
    gamesBehind: "0.0",
    streak: 5,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 21,
      name: "Milwaukee Bucks",
      nickname: "Bucks",
      code: "MIL",
      logo: "https://upload.wikimedia.org/wikipedia/fr/3/34/Bucks2015.png",
    },
    conference: {
      name: EConferences.east,
      rank: 5,
      win: 22,
      loss: 17,
    },
    division: {
      name: "central",
      rank: 3,
      win: 8,
      loss: 3,
      gamesBehind: "2.5",
    },
    win: {
      home: 20,
      away: 16,
      total: 36,
      percentage: ".600",
      lastTen: 6,
    },
    loss: {
      home: 11,
      away: 13,
      total: 24,
      percentage: ".400",
      lastTen: 4,
    },
    gamesBehind: "2.5",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    conference: {
      name: EConferences.east,
      rank: 4,
      win: 20,
      loss: 13,
    },
    division: {
      name: "central",
      rank: 2,
      win: 7,
      loss: 3,
      gamesBehind: "2.5",
    },
    win: {
      home: 18,
      away: 17,
      total: 35,
      percentage: ".603",
      lastTen: 6,
    },
    loss: {
      home: 9,
      away: 14,
      total: 23,
      percentage: ".397",
      lastTen: 4,
    },
    gamesBehind: "2.5",
    streak: 2,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 15,
      name: "Indiana Pacers",
      nickname: "Pacers",
      code: "IND",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/c/cf/Pacers_de_l%27Indiana_logo.svg/1180px-Pacers_de_l%27Indiana_logo.svg.png",
    },
    conference: {
      name: EConferences.east,
      rank: 13,
      win: 9,
      loss: 29,
    },
    division: {
      name: "central",
      rank: 4,
      win: 2,
      loss: 11,
      gamesBehind: "18.5",
    },
    win: {
      home: 14,
      away: 6,
      total: 20,
      percentage: ".333",
      lastTen: 2,
    },
    loss: {
      home: 17,
      away: 23,
      total: 40,
      percentage: ".667",
      lastTen: 8,
    },
    gamesBehind: "18.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 10,
      name: "Detroit Pistons",
      nickname: "Pistons",
      code: "DET",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Detroit_Pistons_primary_logo_2017.png/150px-Detroit_Pistons_primary_logo_2017.png",
    },
    conference: {
      name: EConferences.east,
      rank: 14,
      win: 9,
      loss: 23,
    },
    division: {
      name: "central",
      rank: 5,
      win: 3,
      loss: 7,
      gamesBehind: "24.5",
    },
    win: {
      home: 8,
      away: 5,
      total: 13,
      percentage: ".224",
      lastTen: 2,
    },
    loss: {
      home: 20,
      away: 25,
      total: 45,
      percentage: ".776",
      lastTen: 8,
    },
    gamesBehind: "24.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 19,
      name: "Memphis Grizzlies",
      nickname: "Grizzlies",
      code: "MEM",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/1200px-Memphis_Grizzlies.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 3,
      win: 28,
      loss: 12,
    },
    division: {
      name: "southwest",
      rank: 1,
      win: 6,
      loss: 4,
      gamesBehind: "0.0",
    },
    win: {
      home: 20,
      away: 21,
      total: 41,
      percentage: ".683",
      lastTen: 8,
    },
    loss: {
      home: 10,
      away: 9,
      total: 19,
      percentage: ".317",
      lastTen: 2,
    },
    gamesBehind: "8.0",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 14,
      name: "Houston Rockets",
      nickname: "Rockets",
      code: "HOU",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Houston_Rockets_logo_2003.png/330px-Houston_Rockets_logo_2003.png",
    },
    conference: {
      name: EConferences.west,
      rank: 15,
      win: 7,
      loss: 28,
    },
    division: {
      name: "southwest",
      rank: 5,
      win: 2,
      loss: 8,
      gamesBehind: "25.0",
    },
    win: {
      home: 8,
      away: 7,
      total: 15,
      percentage: ".259",
      lastTen: 1,
    },
    loss: {
      home: 18,
      away: 25,
      total: 43,
      percentage: ".741",
      lastTen: 9,
    },
    gamesBehind: "33.0",
    streak: 7,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 8,
      name: "Dallas Mavericks",
      nickname: "Mavericks",
      code: "DAL",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b8/Mavericks_de_Dallas_logo.svg/150px-Mavericks_de_Dallas_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 5,
      win: 24,
      loss: 14,
    },
    division: {
      name: "southwest",
      rank: 2,
      win: 11,
      loss: 2,
      gamesBehind: "5.5",
    },
    win: {
      home: 20,
      away: 15,
      total: 35,
      percentage: ".593",
      lastTen: 7,
    },
    loss: {
      home: 11,
      away: 13,
      total: 24,
      percentage: ".407",
      lastTen: 3,
    },
    gamesBehind: "13.5",
    streak: 2,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 31,
      name: "San Antonio Spurs",
      nickname: "Spurs",
      code: "SAS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/0/0e/San_Antonio_Spurs_2018.png",
    },
    conference: {
      name: EConferences.west,
      rank: 11,
      win: 14,
      loss: 20,
    },
    division: {
      name: "southwest",
      rank: 3,
      win: 4,
      loss: 6,
      gamesBehind: "17.5",
    },
    win: {
      home: 11,
      away: 12,
      total: 23,
      percentage: ".390",
      lastTen: 5,
    },
    loss: {
      home: 18,
      away: 18,
      total: 36,
      percentage: ".610",
      lastTen: 5,
    },
    gamesBehind: "25.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 23,
      name: "New Orleans Pelicans",
      nickname: "Pelicans",
      code: "NOP",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/2/21/New_Orleans_Pelicans.png/200px-New_Orleans_Pelicans.png",
    },
    conference: {
      name: EConferences.west,
      rank: 12,
      win: 14,
      loss: 20,
    },
    division: {
      name: "southwest",
      rank: 4,
      win: 4,
      loss: 7,
      gamesBehind: "17.5",
    },
    win: {
      home: 13,
      away: 10,
      total: 23,
      percentage: ".390",
      lastTen: 5,
    },
    loss: {
      home: 17,
      away: 19,
      total: 36,
      percentage: ".610",
      lastTen: 5,
    },
    gamesBehind: "25.5",
    streak: 2,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 11,
      name: "Golden State Warriors",
      nickname: "Warriors",
      code: "GSW",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Warriors_de_Golden_State_logo.svg/1200px-Warriors_de_Golden_State_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 2,
      win: 25,
      loss: 11,
    },
    division: {
      name: "pacific",
      rank: 2,
      win: 9,
      loss: 2,
      gamesBehind: "6.5",
    },
    win: {
      home: 26,
      away: 16,
      total: 42,
      percentage: ".712",
      lastTen: 6,
    },
    loss: {
      home: 6,
      away: 11,
      total: 17,
      percentage: ".288",
      lastTen: 4,
    },
    gamesBehind: "6.5",
    streak: 2,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 30,
      name: "Sacramento Kings",
      nickname: "Kings",
      code: "SAC",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/9/95/Kings_de_Sacramento_logo.svg/1200px-Kings_de_Sacramento_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 13,
      win: 15,
      loss: 22,
    },
    division: {
      name: "pacific",
      rank: 5,
      win: 5,
      loss: 7,
      gamesBehind: "27.0",
    },
    win: {
      home: 15,
      away: 7,
      total: 22,
      percentage: ".367",
      lastTen: 4,
    },
    loss: {
      home: 17,
      away: 21,
      total: 38,
      percentage: ".633",
      lastTen: 6,
    },
    gamesBehind: "27.0",
    streak: 2,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 28,
      name: "Phoenix Suns",
      nickname: "Suns",
      code: "PHX",
      logo: "https://upload.wikimedia.org/wikipedia/fr/5/56/Phoenix_Suns_2013.png",
    },
    conference: {
      name: EConferences.west,
      rank: 1,
      win: 28,
      loss: 7,
    },
    division: {
      name: "pacific",
      rank: 1,
      win: 6,
      loss: 4,
      gamesBehind: "0.0",
    },
    win: {
      home: 26,
      away: 22,
      total: 48,
      percentage: ".828",
      lastTen: 9,
    },
    loss: {
      home: 5,
      away: 5,
      total: 10,
      percentage: ".172",
      lastTen: 1,
    },
    gamesBehind: "0.0",
    streak: 7,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 16,
      name: "LA Clippers",
      nickname: "Clippers",
      code: "LAC",
      logo: "https://upload.wikimedia.org/wikipedia/fr/d/d6/Los_Angeles_Clippers_logo_2010.png",
    },
    conference: {
      name: EConferences.west,
      rank: 8,
      win: 17,
      loss: 23,
    },
    division: {
      name: "pacific",
      rank: 3,
      win: 5,
      loss: 6,
      gamesBehind: "19.5",
    },
    win: {
      home: 18,
      away: 12,
      total: 30,
      percentage: ".492",
      lastTen: 5,
    },
    loss: {
      home: 13,
      away: 18,
      total: 31,
      percentage: ".508",
      lastTen: 5,
    },
    gamesBehind: "19.5",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 17,
      name: "Los Angeles Lakers",
      nickname: "Lakers",
      code: "LAL",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/220px-Los_Angeles_Lakers_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 9,
      win: 15,
      loss: 19,
    },
    division: {
      name: "pacific",
      rank: 4,
      win: 2,
      loss: 8,
      gamesBehind: "21.0",
    },
    win: {
      home: 18,
      away: 9,
      total: 27,
      percentage: ".466",
      lastTen: 3,
    },
    loss: {
      home: 13,
      away: 18,
      total: 31,
      percentage: ".534",
      lastTen: 7,
    },
    gamesBehind: "21.0",
    streak: 1,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 40,
      name: "Utah Jazz",
      nickname: "Jazz",
      code: "UTA",
      logo: "https://upload.wikimedia.org/wikipedia/fr/3/3b/Jazz_de_l%27Utah_logo.png",
    },
    conference: {
      name: EConferences.west,
      rank: 4,
      win: 22,
      loss: 12,
    },
    division: {
      name: "northwest",
      rank: 1,
      win: 11,
      loss: 1,
      gamesBehind: "0.0",
    },
    win: {
      home: 21,
      away: 15,
      total: 36,
      percentage: ".621",
      lastTen: 6,
    },
    loss: {
      home: 10,
      away: 12,
      total: 22,
      percentage: ".379",
      lastTen: 4,
    },
    gamesBehind: "12.0",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 22,
      name: "Minnesota Timberwolves",
      nickname: "Timberwolves",
      code: "MIN",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d9/Timberwolves_du_Minnesota_logo_2017.png/200px-Timberwolves_du_Minnesota_logo_2017.png",
    },
    conference: {
      name: EConferences.west,
      rank: 7,
      win: 20,
      loss: 18,
    },
    division: {
      name: "northwest",
      rank: 3,
      win: 7,
      loss: 4,
      gamesBehind: "5.5",
    },
    win: {
      home: 17,
      away: 14,
      total: 31,
      percentage: ".525",
      lastTen: 7,
    },
    loss: {
      home: 11,
      away: 17,
      total: 28,
      percentage: ".475",
      lastTen: 3,
    },
    gamesBehind: "17.5",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 9,
      name: "Denver Nuggets",
      nickname: "Nuggets",
      code: "DEN",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/3/35/Nuggets_de_Denver_2018.png/180px-Nuggets_de_Denver_2018.png",
    },
    conference: {
      name: EConferences.west,
      rank: 6,
      win: 18,
      loss: 17,
    },
    division: {
      name: "northwest",
      rank: 2,
      win: 4,
      loss: 8,
      gamesBehind: "3.0",
    },
    win: {
      home: 16,
      away: 17,
      total: 33,
      percentage: ".569",
      lastTen: 6,
    },
    loss: {
      home: 10,
      away: 15,
      total: 25,
      percentage: ".431",
      lastTen: 4,
    },
    gamesBehind: "15.0",
    streak: 3,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 29,
      name: "Portland Trail Blazers",
      nickname: "Trail Blazers",
      code: "POR",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/1200px-Portland_Trail_Blazers_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 10,
      win: 11,
      loss: 24,
    },
    division: {
      name: "northwest",
      rank: 4,
      win: 1,
      loss: 8,
      gamesBehind: "11.5",
    },
    win: {
      home: 16,
      away: 9,
      total: 25,
      percentage: ".424",
      lastTen: 4,
    },
    loss: {
      home: 16,
      away: 18,
      total: 34,
      percentage: ".576",
      lastTen: 6,
    },
    gamesBehind: "23.5",
    streak: 4,
    winStreak: true,
    tieBreakerPoints: null,
  },
  {
    league: ETeamLeagueNames.standard,
    season: 2021,
    team: {
      id: 25,
      name: "Oklahoma City Thunder",
      nickname: "Thunder",
      code: "OKC",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4f/Thunder_d%27Oklahoma_City_logo.svg/1200px-Thunder_d%27Oklahoma_City_logo.svg.png",
    },
    conference: {
      name: EConferences.west,
      rank: 14,
      win: 13,
      loss: 24,
    },
    division: {
      name: "northwest",
      rank: 5,
      win: 3,
      loss: 5,
      gamesBehind: "18.0",
    },
    win: {
      home: 9,
      away: 9,
      total: 18,
      percentage: ".310",
      lastTen: 4,
    },
    loss: {
      home: 19,
      away: 21,
      total: 40,
      percentage: ".690",
      lastTen: 6,
    },
    gamesBehind: "30.0",
    streak: 1,
    winStreak: false,
    tieBreakerPoints: null,
  },
];

export { standings };
